### ISSUE TITLE
Many tests fail with error due to incorrect use of the HttpClient

### ISSUE THREAD

**Issue by berezovskyi** [eclipse/lyo.testsuite#28]
> `updateCreatedResourceWithInvalidContent[0](org.eclipse.lyo.testsuite.oslcv2.CreationAndUpdateJsonTests): Invalid use of SingleClientConnManager: connection still allocated.(..)`

Stacktrace:

```
java.lang.IllegalStateException: Invalid use of SingleClientConnManager: connection still allocated.
Make sure to release the connection before allocating another one.
	at org.apache.http.impl.conn.SingleClientConnManager.getConnection(SingleClientConnManager.java:216)
	at org.apache.http.impl.conn.SingleClientConnManager$1.getConnection(SingleClientConnManager.java:190)
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:401)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:820)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:754)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:732)
	at org.eclipse.lyo.testsuite.server.util.OSLCUtils.getResponseFromUrl(OSLCUtils.java:163)
	at org.eclipse.lyo.testsuite.oslcv2.SimplifiedQueryJsonTests.validateNonEmptyResponse(SimplifiedQueryJsonTests.java:81)
	at org.eclipse.lyo.testsuite.oslcv2.SimplifiedQueryJsonTests.fullTextSearchContainsExpectedResults(SimplifiedQueryJsonTests.java:147)
```

**Comment by berezovskyi** [comment]
Possible hints: https://stackoverflow.com/questions/21800495/invalid-use-of-singleclientconnmanager-connection-still-allocated
